markdown: kramdown
permalink: /posts/:slug/
show_drafts: true

collections:
  research-notes:
    output: true
    permalink: /research-notes/:slug/
  draft-posts:
    output: true
    permalink: /drafts/:slug/
